apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Release
on:
  workflow_dispatch:
env:
  ORG_ID: 10f39560-4828-4148-92bd-f26e09f05f8f
  APP_ID: 5629a03d-79a9-402b-97fd-9ec515bcb8d4
jobs:
  acme-release-approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 9e6cef82-03d3-11eb-9d67-42010a83ae35,31ede04a-a3ce-11ec-a148-42010a83ae13,c260e366-03d4-11eb-9d67-42010a83ae35,e70bcb3e-4a74-11ed-b1a3-42010a83ae66,69fe7606-13a7-11eb-b8f1-42010a83ae35,1aa39fbc-03d2-11eb-9d67-42010a83ae35,e1a89f4a-03d2-11eb-9d67-42010a83ae35,0cb88e48-03d3-11eb-9d67-42010a83ae35,3122cd3e-2fd6-11ee-ad53-42010a83ae76
      disallowLaunchByUser: false
      instructions: A release has been requested.  Is this approved?
  release:
    steps:
      - name: Deploy linked components
        uses: ./actions/component-dispatch
        with:
          workflows-dispatch-file: deploy.yaml
          token: ${{ secrets.CBP_PAT }}
          org-id: ${{ env.ORG_ID }}
          component-id: ${{ env.APP_ID }}
    needs:
      - acme-release-approval
