apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:

env:
  ORG_ID: "484e57bd-7b0b-4a37-448b-ab8ca8f9a684"
  APP_ID: "dcaf825d-c6a1-43bd-8fb6-016e8a66335e"

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: Get application
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          set -x
          curl -H "Authorization: Bearer ${{ secrets.CBP_PAT }}" -H "Accept: application/json" ${{ cloudbees.api.url }}/v1/organizations/$ORG_ID/services/$APP_ID | jq

