apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Release
on:
  workflow_dispatch:
env:
  ORG_ID: 10f39560-4828-4148-92bd-f26e09f05f8f
  APP_ID: 5629a03d-79a9-402b-97fd-9ec515bcb8d4
jobs:
  release:
    steps:
      - name: Deploy linked components
        uses: ./actions/component-dispatch
        with:
          workflows-dispatch-file: deploy.yaml
          token: ${{ secrets.CBP_PAT }}
          org-id: ${{ env.ORG_ID }}
          component-id: ${{ env.APP_ID }}
