apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Release
on:
  workflow_dispatch:
env:
  ORG_ID: 484e57bd-7b0b-4a37-448b-ab8ca8f9a684
  APP_ID: dcaf825d-c6a1-43bd-8fb6-016e8a66335e
jobs:
  release:
    steps:
      - name: Deploy linked components
        uses: ./actions/component-dispatch
        with:
          workflows-dispatch-file: deploy.yaml
          token: ${{ secrets.CBP_PAT }}
          org-id: ${{ env.ORG_ID }}
          component-id: ${{ env.APP_ID }}
