apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
env:
  ORG_ID: 484e57bd-7b0b-4a37-448b-ab8ca8f9a684
  APP_ID: dcaf825d-c6a1-43bd-8fb6-016e8a66335e
jobs:
  release:
    steps:
      - name: Calculate dispatch JSON
        id: dispatch_json
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          set -x
          curl -H "Authorization: Bearer ${{ secrets.CBP_PAT }}" -H "Accept: application/json" ${{ cloudbees.api.url }}/v1/organizations/$ORG_ID/services/$APP_ID | jq -r '[.service.linkedComponentIds[] | {"component_id": .,"branch_name": "main", "workflow_file_name": "deploy.yaml"}]' | jq > $CLOUDBEES_OUTPUTS/dispatch
          cat $CLOUDBEES_OUTPUTS/dispatch
      - name: Save deploy file
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          echo "Saving dispatch as file..."
          echo '${{steps.dispatch_json.outputs.dispatch}}' > dispatch_requests.json
          echo "dump workspace dispatch file..."
          cat dispatch_requests.json
      - name: Dispatch Workflows
        uses: cloudbees-io/workflows-dispatch@main
        with:
          workflows-dispatch-file: dispatch_requests.json
          token: ${{ secrets.CBP_PAT }}
    needs:
      - deployment-approval
  deployment-approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 69fe7606-13a7-11eb-b8f1-42010a83ae35
      disallowLaunchByUser: false
      instructions: Approved?
